use bevy::log::*;
use bevy::input::mouse::*;
use bevy::input::keyboard::*;


pub(crate) fn to_mouse(mb: u16) -> MouseButton {
  match mb {
    0 => MouseButton::Left,
    1 => MouseButton::Middle,
    2 => MouseButton::Right,
    3 => MouseButton::Back,
    4 => MouseButton::Forward,
    _ => MouseButton::Other(mb),
  }
}


pub(crate)  fn to_key(key: &str) -> Key {
  match key {
    "Escape"             => Key::Escape,
    "F1"                 => Key::F1,
    "F2"                 => Key::F2,
    "F3"                 => Key::F3,
    "F4"                 => Key::F4,
    "F5"                 => Key::F5,
    "F6"                 => Key::F6,
    "F7"                 => Key::F7,
    "F8"                 => Key::F8,
    "F9"                 => Key::F9,
    "F10"                => Key::F10,
    "F11"                => Key::F11,
    "F12"                => Key::F12,
    "F13"                => Key::F13,
    "F14"                => Key::F14,
    "F15"                => Key::F15,
    "F16"                => Key::F16,
    "F17"                => Key::F17,
    "F18"                => Key::F18,
    "F19"                => Key::F19,
    "F20"                => Key::F20,
    "F21"                => Key::F21,
    "F22"                => Key::F22,
    "F23"                => Key::F23,
    "F24"                => Key::F24,
    "F25"                => Key::F25,
    "F26"                => Key::F26,
    "F27"                => Key::F27,
    "F28"                => Key::F28,
    "F29"                => Key::F29,
    "F30"                => Key::F30,
    "F31"                => Key::F31,
    "F32"                => Key::F32,
    "F33"                => Key::F33,
    "F34"                => Key::F34,
    "F35"                => Key::F35,
    "PrintScreen"        => Key::PrintScreen,
    "ScrollLock"         => Key::ScrollLock,
    "Pause"              => Key::Pause,
    "LaunchApplication1" => Key::LaunchApplication1,
    "LaunchApplication2" => Key::LaunchApplication2,
    "MediaPlayPause"     => Key::MediaPlayPause,
    "MediaStop"          => Key::MediaStop,
    "AudioVolumeDown"    => Key::AudioVolumeDown,
    "AudioVolumeUp"      => Key::AudioVolumeUp,
    "AudioVolumeMute"    => Key::AudioVolumeMute,
    "Enter"              => Key::Enter,
    "Backspace"          => Key::Backspace,
    "Tab"                => Key::Tab,
    "Shift"              => Key::Shift,
    "Control"            => Key::Control,
    "Alt"                => Key::Alt,
    "CapsLock"           => Key::CapsLock,
    "Meta"               => Key::Meta,
    "ContextMenu"        => Key::ContextMenu,
    "Space"              => Key::Space,
    "Insert"             => Key::Insert,
    "Delete"             => Key::Delete,
    "Home"               => Key::Home,
    "End"                => Key::End,
    "PageUp"             => Key::PageUp,
    "PageDown"           => Key::PageDown,
    "NumLock"            => Key::NumLock,
    "Clear"              => Key::Clear,
    "ArrowLeft"          => Key::ArrowLeft,
    "ArrowUp"            => Key::ArrowUp,
    "ArrowRight"         => Key::ArrowRight,
    "ArrowDown"          => Key::ArrowDown,
    ch if ch.len() == 1  => Key::Character(ch[0..1].into()),

    k => {
      if k != "Unidentified" { warn!("Unhandled key: {k:?}"); }
      Key::Unidentified(NativeKey::Unidentified)
    }
  }
}


pub(crate) fn to_keycode(keycode: &str) -> KeyCode {
  match keycode {
    "Escape"             => KeyCode::Escape,
    "F1"                 => KeyCode::F1,
    "F2"                 => KeyCode::F2,
    "F3"                 => KeyCode::F3,
    "F4"                 => KeyCode::F4,
    "F5"                 => KeyCode::F5,
    "F6"                 => KeyCode::F6,
    "F7"                 => KeyCode::F7,
    "F8"                 => KeyCode::F8,
    "F9"                 => KeyCode::F9,
    "F10"                => KeyCode::F10,
    "F11"                => KeyCode::F11,
    "F12"                => KeyCode::F12,
    "F13"                => KeyCode::F13,
    "F14"                => KeyCode::F14,
    "F15"                => KeyCode::F15,
    "F16"                => KeyCode::F16,
    "F17"                => KeyCode::F17,
    "F18"                => KeyCode::F18,
    "F19"                => KeyCode::F19,
    "F20"                => KeyCode::F20,
    "F21"                => KeyCode::F21,
    "F22"                => KeyCode::F22,
    "F23"                => KeyCode::F23,
    "F24"                => KeyCode::F24,
    "F25"                => KeyCode::F25,
    "F26"                => KeyCode::F26,
    "F27"                => KeyCode::F27,
    "F28"                => KeyCode::F28,
    "F29"                => KeyCode::F29,
    "F30"                => KeyCode::F30,
    "F31"                => KeyCode::F31,
    "F32"                => KeyCode::F32,
    "F33"                => KeyCode::F33,
    "F34"                => KeyCode::F34,
    "F35"                => KeyCode::F35,
    "PrintScreen"        => KeyCode::PrintScreen,
    "ScrollLock"         => KeyCode::ScrollLock,
    "Pause"              => KeyCode::Pause,
    "LaunchApplication1" => KeyCode::LaunchApp1,
    "LaunchApplication2" => KeyCode::LaunchApp2,
    "MediaPlayPause"     => KeyCode::MediaPlayPause,
    "MediaStop"          => KeyCode::MediaStop,
    "AudioVolumeDown"    => KeyCode::AudioVolumeDown,
    "AudioVolumeUp"      => KeyCode::AudioVolumeUp,
    "AudioVolumeMute"    => KeyCode::AudioVolumeMute,
    "Backquote"          => KeyCode::Backquote,
    "Digit1"             => KeyCode::Digit1,
    "Digit2"             => KeyCode::Digit2,
    "Digit3"             => KeyCode::Digit3,
    "Digit4"             => KeyCode::Digit4,
    "Digit5"             => KeyCode::Digit5,
    "Digit6"             => KeyCode::Digit6,
    "Digit7"             => KeyCode::Digit7,
    "Digit8"             => KeyCode::Digit8,
    "Digit9"             => KeyCode::Digit9,
    "Digit0"             => KeyCode::Digit0,
    "Equal"              => KeyCode::Equal,
    "Minus"              => KeyCode::Minus,
    "Backspace"          => KeyCode::Backspace,
    "Tab"                => KeyCode::Tab,
    "KeyQ"               => KeyCode::KeyQ,
    "KeyW"               => KeyCode::KeyW,
    "KeyE"               => KeyCode::KeyE,
    "KeyR"               => KeyCode::KeyR,
    "KeyT"               => KeyCode::KeyT,
    "KeyY"               => KeyCode::KeyY,
    "KeyU"               => KeyCode::KeyU,
    "KeyI"               => KeyCode::KeyI,
    "KeyO"               => KeyCode::KeyO,
    "KeyP"               => KeyCode::KeyP,
    "BracketLeft"        => KeyCode::BracketLeft,
    "BracketRight"       => KeyCode::BracketRight,
    "Backslash"          => KeyCode::Backslash,
    "CapsLock"           => KeyCode::CapsLock,
    "KeyA"               => KeyCode::KeyA,
    "KeyS"               => KeyCode::KeyS,
    "KeyD"               => KeyCode::KeyD,
    "KeyF"               => KeyCode::KeyF,
    "KeyG"               => KeyCode::KeyG,
    "KeyH"               => KeyCode::KeyH,
    "KeyJ"               => KeyCode::KeyJ,
    "KeyK"               => KeyCode::KeyK,
    "KeyL"               => KeyCode::KeyL,
    "Semicolon"          => KeyCode::Semicolon,
    "Quote"              => KeyCode::Quote,
    "Enter"              => KeyCode::Enter,
    "ShiftLeft"          => KeyCode::ShiftLeft,
    "KeyZ"               => KeyCode::KeyZ,
    "KeyX"               => KeyCode::KeyX,
    "KeyC"               => KeyCode::KeyC,
    "KeyV"               => KeyCode::KeyV,
    "KeyB"               => KeyCode::KeyB,
    "KeyN"               => KeyCode::KeyN,
    "KeyM"               => KeyCode::KeyM,
    "Comma"              => KeyCode::Comma,
    "Period"             => KeyCode::Period,
    "Slash"              => KeyCode::Slash,
    "ShiftRight"         => KeyCode::ShiftRight,
    "ControlLeft"        => KeyCode::ControlLeft,
    "MetaLeft"           => KeyCode::SuperLeft,
    "AltLeft"            => KeyCode::AltLeft,
    "Space"              => KeyCode::Space,
    "AltRight"           => KeyCode::AltRight,
    "ContextMenu"        => KeyCode::ContextMenu,
    "ControlRight"       => KeyCode::ControlRight,
    "Insert"             => KeyCode::Insert,
    "Delete"             => KeyCode::Delete,
    "Home"               => KeyCode::Home,
    "End"                => KeyCode::End,
    "PageUp"             => KeyCode::PageUp,
    "PageDown"           => KeyCode::PageDown,
    "ArrowLeft"          => KeyCode::ArrowLeft,
    "ArrowUp"            => KeyCode::ArrowUp,
    "ArrowRight"         => KeyCode::ArrowRight,
    "ArrowDown"          => KeyCode::ArrowDown,
    "NumLock"            => KeyCode::NumLock,
    "Numpad1"            => KeyCode::Numpad1,
    "Numpad2"            => KeyCode::Numpad2,
    "Numpad3"            => KeyCode::Numpad3,
    "Numpad4"            => KeyCode::Numpad4,
    "Numpad5"            => KeyCode::Numpad5,
    "Numpad6"            => KeyCode::Numpad6,
    "Numpad7"            => KeyCode::Numpad7,
    "Numpad8"            => KeyCode::Numpad8,
    "Numpad9"            => KeyCode::Numpad9,
    "Numpad0"            => KeyCode::Numpad0,
    "NumpadAdd"          => KeyCode::NumpadAdd,
    "NumpadSubtract"     => KeyCode::NumpadSubtract,
    "NumpadMultiply"     => KeyCode::NumpadMultiply,
    "NumpadDivide"       => KeyCode::NumpadDivide,
    "NumpadEnter"        => KeyCode::NumpadEnter,
    "NumpadDecimal"      => KeyCode::NumpadDecimal,
    "NumpadComma"        => KeyCode::NumpadComma,
    "NumpadEqual"        => KeyCode::NumpadEqual,
    c => {
      if c != "Unidentified" { warn!("Unhandled code: {c:?}"); }
      KeyCode::Unidentified(NativeKeyCode::Unidentified)
    },
  }
}
